management:
  context-path: /sysinfo

spring:
  datasource:
    url:   jdbc:derby://localhost:1527/C:/Users/taveraj/Downloads/respaldo_derby/comics_db
    username: app
    password: derby
    driver-class-name: org.apache.derby.jdbc.ClientDriver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

server:
  port: 8000    