INSERT INTO PERIODICIDAD (descripcion,tiempo) VALUES('mensual',4);
INSERT INTO PERIODICIDAD (descripcion,tiempo) VALUES('semanal',1);
INSERT INTO PERIODICIDAD (descripcion,tiempo) VALUES('bimestral',8);
INSERT INTO PERIODICIDAD (descripcion,tiempo) VALUES('trimestral',12);
INSERT INTO PERIODICIDAD (descripcion,tiempo) VALUES('semestral',24);
INSERT INTO PERIODICIDAD (descripcion,tiempo) VALUES('tetramestral',16);
INSERT INTO PERIODICIDAD (descripcion,tiempo) VALUES('anual',48);
INSERT INTO PERIODICIDAD (descripcion,tiempo) VALUES('quincenal',2);


INSERT INTO EDITORIAL (nombre) VALUES('Panini');
INSERT INTO EDITORIAL (nombre) VALUES('Marvel Mexico');
INSERT INTO EDITORIAL (nombre) VALUES('Kamite');
INSERT INTO EDITORIAL (nombre) VALUES('DC Mexico');
INSERT INTO EDITORIAL (nombre) VALUES('Vértigo México');
INSERT INTO EDITORIAL (nombre) VALUES('Smash Manga');

SELECT * FROM COMIC WHERE ID_COMIC IN(47,1,6);
DELETE COMIC WHERE ID_COMIC IN(47,1,6);;

INSERT INTO COMIC (TITULO,ID_PERIODICIDAD,PRECIO,ID_EDITORIAL,EN_PUBLICACION,NUMERO_INICIAL) VALUES ('Berserk',3,85.0,1,1,1);
INSERT INTO COMIC (TITULO,ID_PERIODICIDAD,PRECIO,ID_EDITORIAL,EN_PUBLICACION,NUMERO_INICIAL) VALUES ('Extraordinary X Men',1,29.0,2,1,1);
INSERT INTO COMIC (TITULO,ID_PERIODICIDAD,PRECIO,ID_EDITORIAL,EN_PUBLICACION,NUMERO_INICIAL) VALUES ('Deadpool',1,53.0,2,1,1);
INSERT INTO COMIC (TITULO,ID_PERIODICIDAD,PRECIO,ID_EDITORIAL,EN_PUBLICACION,NUMERO_INICIAL) VALUES ('Old Man Logan',1,29.0,2,1,1);
INSERT INTO COMIC (TITULO,ID_PERIODICIDAD,PRECIO,ID_EDITORIAL,EN_PUBLICACION,NUMERO_INICIAL) VALUES ('Miss Marvel',1,29.0,2,1,1);
INSERT INTO COMIC (TITULO,ID_PERIODICIDAD,PRECIO,ID_EDITORIAL,EN_PUBLICACION,NUMERO_INICIAL) VALUES ('Spiderman / Deadpool',1,29.0,2,1,1);
INSERT INTO COMIC (TITULO,ID_PERIODICIDAD,PRECIO,ID_EDITORIAL,EN_PUBLICACION,NUMERO_INICIAL) VALUES ('Daredevil',1,29.0,2,1,1);
INSERT INTO COMIC (TITULO,ID_PERIODICIDAD,PRECIO,ID_EDITORIAL,EN_PUBLICACION,NUMERO_INICIAL) VALUES ('Doctor Strange',1,29.0,2,1,1);
INSERT INTO COMIC (TITULO,ID_PERIODICIDAD,PRECIO,ID_EDITORIAL,EN_PUBLICACION,NUMERO_INICIAL) VALUES ('Thor',1,29.0,2,1,1);
INSERT INTO COMIC (TITULO,ID_PERIODICIDAD,PRECIO,ID_EDITORIAL,EN_PUBLICACION,NUMERO_INICIAL,NUMERO_FINAL) VALUES ('Sombra',1,33.0,3,1,1,4);
INSERT INTO COMIC (TITULO,ID_PERIODICIDAD,PRECIO,ID_EDITORIAL,EN_PUBLICACION,NUMERO_INICIAL) VALUES ('One Punch Man',4,99.0,1,1,1);
INSERT INTO COMIC (TITULO,ID_PERIODICIDAD,PRECIO,ID_EDITORIAL,EN_PUBLICACION,NUMERO_INICIAL) VALUES ('Adlt: Before The Fall',4,99.0,1,1,1);
INSERT INTO COMIC (TITULO,ID_PERIODICIDAD,PRECIO,ID_EDITORIAL,EN_PUBLICACION,NUMERO_INICIAL) VALUES ('Aijin',4,99.0,1,1,1);
INSERT INTO COMIC (TITULO,ID_PERIODICIDAD,PRECIO,ID_EDITORIAL,EN_PUBLICACION,NUMERO_INICIAL,NUMERO_FINAL) VALUES ('N.G. Evangelion',1,99.0,1,1,1,11);
INSERT INTO COMIC (TITULO,ID_PERIODICIDAD,PRECIO,ID_EDITORIAL,EN_PUBLICACION,NUMERO_INICIAL,NUMERO_FINAL) VALUES ('Naruto',1,99.0,1,1,1,72);
INSERT INTO COMIC (TITULO,ID_PERIODICIDAD,PRECIO,ID_EDITORIAL,EN_PUBLICACION,NUMERO_INICIAL,NUMERO_FINAL) VALUES ('Sw Presnta Han Solo',1,39.0,1,1,1,4);
INSERT INTO COMIC (TITULO,ID_PERIODICIDAD,PRECIO,ID_EDITORIAL,EN_PUBLICACION,NUMERO_INICIAL) VALUES ('My Hero Academia',3,99.0,1,1,1);
INSERT INTO COMIC (TITULO,ID_PERIODICIDAD,PRECIO,ID_EDITORIAL,EN_PUBLICACION,NUMERO_INICIAL) VALUES ('The Walking Dead',2,150.0,3,0,1);
INSERT INTO COMIC (TITULO,ID_PERIODICIDAD,PRECIO,ID_EDITORIAL,EN_PUBLICACION,NUMERO_INICIAL,NUMERO_FINAL) VALUES ('Sailor Moon',1,99.0,1,1,1,12);
INSERT INTO COMIC (TITULO,ID_PERIODICIDAD,PRECIO,ID_EDITORIAL,EN_PUBLICACION,NUMERO_INICIAL,NUMERO_FINAL) VALUES ('Kyoukai No Rinne',1,85.0,1,1,1,42);
INSERT INTO COMIC (TITULO,ID_PERIODICIDAD,PRECIO,ID_EDITORIAL,EN_PUBLICACION,NUMERO_INICIAL,NUMERO_FINAL) VALUES ('Ranma 1/2',1,85.0,1,1,1,32);
INSERT INTO COMIC (TITULO,ID_PERIODICIDAD,PRECIO,ID_EDITORIAL,EN_PUBLICACION,NUMERO_INICIAL) VALUES ('Ataque Titanes',1,85.0,1,1,1);
INSERT INTO COMIC (TITULO,ID_PERIODICIDAD,PRECIO,ID_EDITORIAL,EN_PUBLICACION,NUMERO_INICIAL,NUMERO_FINAL) VALUES ('Preacher',5,369.0,4,5,6,1);
INSERT INTO COMIC (TITULO,ID_PERIODICIDAD,PRECIO,ID_EDITORIAL,EN_PUBLICACION,NUMERO_INICIAL) VALUES ('Injustice Año 3 Vol2',6,169.0,4,0,1);
INSERT INTO COMIC (TITULO,ID_PERIODICIDAD,PRECIO,ID_EDITORIAL,EN_PUBLICACION,NUMERO_INICIAL,NUMERO_FINAL) VALUES ('Manhattan Proyect',1,35.0,1,3,1,7);
INSERT INTO COMIC (TITULO,ID_PERIODICIDAD,PRECIO,ID_EDITORIAL,EN_PUBLICACION,NUMERO_INICIAL,NUMERO_FINAL) VALUES ('Crimson',5,299.0,3,1,1,3);
INSERT INTO COMIC (TITULO,ID_PERIODICIDAD,PRECIO,ID_EDITORIAL,EN_PUBLICACION,NUMERO_INICIAL) VALUES ('Captain América',1,29.0,2,1,1);
INSERT INTO COMIC (TITULO,ID_PERIODICIDAD,PRECIO,ID_EDITORIAL,EN_PUBLICACION,NUMERO_INICIAL) VALUES ('Poe Dameron',1,139.0,1,1,1);
INSERT INTO COMIC (TITULO,ID_PERIODICIDAD,PRECIO,ID_EDITORIAL,EN_PUBLICACION,NUMERO_INICIAL) VALUES ('Seven Deadly Sins',1,85.0,1,1,1);
INSERT INTO COMIC (TITULO,ID_PERIODICIDAD,PRECIO,ID_EDITORIAL,EN_PUBLICACION,NUMERO_INICIAL,NUMERO_FINAL) VALUES ('Captain Tsubasa',1,85.0,1,1,1,37);
INSERT INTO COMIC (TITULO,ID_PERIODICIDAD,PRECIO,ID_EDITORIAL,EN_PUBLICACION,NUMERO_INICIAL,NUMERO_FINAL) VALUES ('Lock & Key',1,259.0,1,1,1,6);
INSERT INTO COMIC (TITULO,ID_PERIODICIDAD,PRECIO,ID_EDITORIAL,EN_PUBLICACION,NUMERO_INICIAL) VALUES ('Outcast',3,33.0,3,1,1);
INSERT INTO COMIC (TITULO,ID_PERIODICIDAD,PRECIO,ID_EDITORIAL,EN_PUBLICACION,NUMERO_INICIAL,NUMERO_FINAL) VALUES ('Valerian',1,169.0,2,1,1,7);
INSERT INTO COMIC (TITULO,ID_PERIODICIDAD,PRECIO,ID_EDITORIAL,EN_PUBLICACION,NUMERO_INICIAL,NUMERO_FINAL) VALUES ('October Faction',1,38.0,3,1,1,18);
INSERT INTO COMIC (TITULO,ID_PERIODICIDAD,PRECIO,ID_EDITORIAL,EN_PUBLICACION,NUMERO_INICIAL,NUMERO_FINAL) VALUES ('Swampthing',7,169.0,5,1,1,6);
INSERT INTO COMIC (TITULO,ID_PERIODICIDAD,PRECIO,ID_EDITORIAL,EN_PUBLICACION,NUMERO_INICIAL) VALUES ('Pretty Deadly ',3,36.0,3,1,1);
INSERT INTO COMIC (TITULO,ID_PERIODICIDAD,PRECIO,ID_EDITORIAL,EN_PUBLICACION,NUMERO_INICIAL) VALUES ('Outcast ',3,33.0,3,1,1);
INSERT INTO COMIC (TITULO,ID_PERIODICIDAD,PRECIO,ID_EDITORIAL,EN_PUBLICACION,NUMERO_INICIAL) VALUES ('Transmetropolitan',7,169.0,5,1,1);
INSERT INTO COMIC (TITULO,ID_PERIODICIDAD,PRECIO,ID_EDITORIAL,EN_PUBLICACION,NUMERO_INICIAL) VALUES ('Bestiarius',4,99.0,1,1,1);
INSERT INTO COMIC (TITULO,ID_PERIODICIDAD,PRECIO,ID_EDITORIAL,EN_PUBLICACION,NUMERO_INICIAL) VALUES ('X Men Prime',1,39.0,2,1,1);
INSERT INTO COMIC (TITULO,ID_PERIODICIDAD,PRECIO,ID_EDITORIAL,EN_PUBLICACION,NUMERO_INICIAL,NUMERO_FINAL) VALUES ('Torpedo 1986',5,289.0,1,1,1,4);
INSERT INTO COMIC (TITULO,ID_PERIODICIDAD,PRECIO,ID_EDITORIAL,EN_PUBLICACION,NUMERO_INICIAL,NUMERO_FINAL) VALUES ('Hunter X Hunter',1,85.0,1,1,1,34);
INSERT INTO COMIC (TITULO,ID_PERIODICIDAD,PRECIO,ID_EDITORIAL,EN_PUBLICACION,NUMERO_INICIAL,NUMERO_FINAL) VALUES ('Zelda',3,169.0,1,1,1,5);
INSERT INTO COMIC (TITULO,ID_PERIODICIDAD,PRECIO,ID_EDITORIAL,EN_PUBLICACION,NUMERO_INICIAL) VALUES ('Doom Patrol ',7,169.0,5,1,1);
INSERT INTO COMIC (TITULO,ID_PERIODICIDAD,PRECIO,ID_EDITORIAL,EN_PUBLICACION,NUMERO_INICIAL,NUMERO_FINAL) VALUES ('Kanan TPB',4,149.0,1,1,1,2);
INSERT INTO COMIC (TITULO,ID_PERIODICIDAD,PRECIO,ID_EDITORIAL,EN_PUBLICACION,NUMERO_INICIAL) VALUES ('Deadly Class',4,189.0,1,1,1);
INSERT INTO COMIC (TITULO,ID_PERIODICIDAD,PRECIO,ID_EDITORIAL,EN_PUBLICACION,NUMERO_INICIAL,NUMERO_FINAL) VALUES ('Star Wars Manga',4,69.0,1,1,1,4);
INSERT INTO COMIC (TITULO,ID_PERIODICIDAD,PRECIO,ID_EDITORIAL,EN_PUBLICACION,NUMERO_INICIAL) VALUES ('Hulk',1,29.0,2,1,1);
INSERT INTO COMIC (TITULO,ID_PERIODICIDAD,PRECIO,ID_EDITORIAL,EN_PUBLICACION,NUMERO_INICIAL,NUMERO_FINAL) VALUES ('Southern Bastards',5,219.0,1,1,1,4);
INSERT INTO COMIC (TITULO,ID_PERIODICIDAD,PRECIO,ID_EDITORIAL,EN_PUBLICACION,NUMERO_INICIAL,NUMERO_FINAL) VALUES ('Blade Of The Inmortal',4,199.0,1,1,1,15);
INSERT INTO COMIC (TITULO,ID_PERIODICIDAD,PRECIO,ID_EDITORIAL,EN_PUBLICACION,NUMERO_INICIAL,NUMERO_FINAL) VALUES ('Akira',5,399.0,1,1,1,6);
INSERT INTO COMIC (TITULO,ID_PERIODICIDAD,PRECIO,ID_EDITORIAL,EN_PUBLICACION,NUMERO_INICIAL) VALUES ('Izombie',7,239.0,5,1,1);
INSERT INTO COMIC (TITULO,ID_PERIODICIDAD,PRECIO,ID_EDITORIAL,EN_PUBLICACION,NUMERO_INICIAL,NUMERO_FINAL) VALUES ('Dark Knight Returns',1,219.0,1,4,1,1);
INSERT INTO COMIC (TITULO,ID_PERIODICIDAD,PRECIO,ID_EDITORIAL,EN_PUBLICACION,NUMERO_INICIAL,NUMERO_FINAL) VALUES ('DKIII',2,69.0,4,1,1,9);


SELECT usu.USUARIO,com.TITULO,com.NUMERO_INICIAL, com.NUMERO_FINAL, cal.FECHA_PUBLICAR FROM CALENDARIO cal, USUARIOS usu, COMIC com WHERE cal.ID_USUARIO=usu.ID_USUARIO AND cal.ID_COMIC=com.ID_COMIC AND usu.USUARIO = 'Tankubetor';
SELECT com.TITULO FROM USUARIOS usu,BIBLIOTECA bib, COMIC com 
WHERE bib.ID_USUARIO = usu.ID_USUARIO 
AND com.ID_COMIC=bib.ID_COMIC
AND usu.USUARIO='Tankubetor';
SELECT * FROM USUARIOS WHERE ID_USUARIO NOT IN(SELECT DISTINCT(ID_USUARIO) FROM CALENDARIO);

SELECT * FROM CALENDARIO WHERE ID_USUARIO = 47;
SELECT DISTINCT(ID_USUARIO) FROM CALENDARIO;

INSERT INTO CALENDARIO (ID_COMIC,ID_USUARIO,FECHA_PUBLICAR,NUMERO) VALUES (1,47,CURRENT_DATE,4);
INSERT INTO CALENDARIO (ID_COMIC,ID_USUARIO,FECHA_PUBLICAR,NUMERO) VALUES (2,47,CURRENT_DATE,7);
INSERT INTO CALENDARIO (ID_COMIC,ID_USUARIO,FECHA_PUBLICAR,NUMERO) VALUES (3,47,CURRENT_DATE,1);
INSERT INTO CALENDARIO (ID_COMIC,ID_USUARIO,FECHA_PUBLICAR,NUMERO) VALUES (4,47,CURRENT_DATE,9);
INSERT INTO CALENDARIO (ID_COMIC,ID_USUARIO,FECHA_PUBLICAR,NUMERO) VALUES (5,47,CURRENT_DATE,20);

SELECT p.* FROM PERIODICIDAD p, COMIC c WHERE p.ID_PERIODICIDAD = c.ID_PERIODICIDAD AND c.ID_COMIC IN(47,1,6);

SELECT * FROM USUARIOS WHERE USUARIO='prueba1u';


SELECT * FROM COMIC;

select usuario0_.id_usuario, usuario0_.password, usuario0_.usuario from usuarios usuario0_ where usuario0_.usuario='Tankubetor';
select comics0_.id_usuario, comics0_.id_comic, comic1_.id_comic, comic1_.id_editorial, comic1_.en_publicacion, comic1_.numero_final, comic1_.numero_inicial, comic1_.id_periodicidad, comic1_.precio, comic1_.titulo, editorial2_.id_editorial, editorial2_.nombre, periodicid3_.id_periodicidad, periodicid3_.descripcion, periodicid3_.tiempo 
from biblioteca comics0_ 
inner join comic comic1_ on comics0_.id_comic=comic1_.id_comic 
left outer join editorial editorial2_ on comic1_.id_editorial=editorial2_.id_editorial 
left outer join periodicidad periodicid3_ on comic1_.id_periodicidad=periodicid3_.id_periodicidad 
where comics0_.id_usuario=46;

SELECT c.* FROM BIBLIOTECA B ,USUARIOS u, COMIC c WHERE 
u.ID_USUARIO = b.ID_USUARIO
AND c.ID_COMIC = b.ID_COMIC
AND b.ID_USUARIO = 46;

SELECT * FROM BIBLIOTECA WHERE ID_USUARIO = 46;
UPDATE BIBLIOTECA SET FALTANTES='1,5,9,10' WHERE ID_USUARIO = 46 AND ID_COMIC = 36;
UPDATE BIBLIOTECA SET FALTANTES='15,39,50' WHERE ID_USUARIO = 46 AND ID_COMIC = 51; 
SELECT * FROM USUARIOS WHERE ID_USUARIO=51;

Hibernate: select calendario0_.id_usuario as id_usuar2_1_0_, calendario0_.id_comic as id_comic1_1_0_, calendario0_.id_comic as id_comic1_1_1_, calendario0_.id_usuario as id_usuar2_1_1_, calendario0_.fecha_publicar as fecha_pu3_1_1_, comic1_.id_comic as id_comic1_3_2_, comic1_.id_editorial as id_edito7_3_2_, comic1_.en_publicacion as en_publi2_3_2_, comic1_.numero_final as numero_f3_3_2_, comic1_.numero_inicial as numero_i4_3_2_, comic1_.id_periodicidad as id_perio8_3_2_, comic1_.precio as precio5_3_2_, comic1_.titulo as titulo6_3_2_, editorial2_.id_editorial as id_edito1_4_3_, editorial2_.nombre as nombre2_4_3_, periodicid3_.id_periodicidad as id_perio1_5_4_, periodicid3_.descripcion as descripc2_5_4_, periodicid3_.tiempo as tiempo3_5_4_ from calendario calendario0_ left outer join comic comic1_ on calendario0_.id_comic=comic1_.id_comic left outer join editorial editorial2_ on comic1_.id_editorial=editorial2_.id_editorial left outer join periodicidad periodicid3_ on comic1_.id_periodicidad=periodicid3_.id_periodicidad where calendario0_.id_usuario=?

SELECT * FROM BIBLIOTECA WHERE ID_USUARIO = 46;

--Consulta que consulta los comics que tiene en su biblioteca el usuario
SELECT c.ID_COMIC,c.TITULO,c.PRECIO,b.FALTANTES,e.NOMBRE EDITORIAL,p.DESCRIPCION PERIODICIDAD FROM COMIC c 
INNER JOIN BIBLIOTECA b ON c.ID_COMIC=b.ID_COMIC AND b.ID_USUARIO=46
INNER JOIN PERIODICIDAD p ON c.ID_PERIODICIDAD = p.ID_PERIODICIDAD
INNER JOIN EDITORIAL e ON c.ID_EDITORIAL = e.ID_EDITORIAL;

SELECT * FROM CALENDARIO WHERE ID_USUARIO = 47;
/*
16 
44 
6  
1  
2  
3  
4  
5  
47 
 */
SELECT * FROM BIBLIOTECA WHERE ID_USUARIO = 47;
INSERT INTO BIBLIOTECA (ID_USUARIO,ID_COMIC) VALUES (47,16);
INSERT INTO BIBLIOTECA (ID_USUARIO,ID_COMIC) VALUES (47,44);
INSERT INTO BIBLIOTECA (ID_USUARIO,ID_COMIC) VALUES (47,6);
INSERT INTO BIBLIOTECA (ID_USUARIO,ID_COMIC) VALUES (47,1);
INSERT INTO BIBLIOTECA (ID_USUARIO,ID_COMIC) VALUES (47,2);
INSERT INTO BIBLIOTECA (ID_USUARIO,ID_COMIC) VALUES (47,3);
INSERT INTO BIBLIOTECA (ID_USUARIO,ID_COMIC) VALUES (47,4);
INSERT INTO BIBLIOTECA (ID_USUARIO,ID_COMIC) VALUES (47,5);



INSERT INTO CALENDARIO (ID_COMIC,ID_USUARIO,FECHA_PUBLICAR,NUMERO) VALUES (47,47,CURRENT_DATE,20);

SELECT c.ID_COMIC,c.TITULO,p.DESCRIPCION periodicidad,e.NOMBRE EDITORIAL,b.FALTANTES,cal.FECHA_PUBLICAR FROM BIBLIOTECA b 
INNER JOIN COMIC c ON c.ID_COMIC = b.ID_COMIC AND b.ID_USUARIO = 51
INNER JOIN PERIODICIDAD p ON c.ID_PERIODICIDAD = p.ID_PERIODICIDAD
INNER JOIN EDITORIAL e ON c.ID_EDITORIAL = e.ID_EDITORIAL
INNER JOIN CALENDARIO cal ON cal.ID_USUARIO = b.ID_USUARIO AND cal.ID_COMIC=b.ID_COMIC;


INSERT INTO CALENDARIO (ID_COMIC,ID_USUARIO,FECHA_PUBLICAR,NUMERO) VALUES (4,46,CURRENT_DATE,1);

SELECT * FROM CALENDARIO WHERE FECHA_PUBLICAR BETWEEN '2018-07-29' AND '2018-09-09' AND ID_USUARIO= 47;


INSERT INTO CALENDARIO (ID_COMIC,ID_USUARIO,FECHA_PUBLICAR,NUMERO) VALUES (36,46,CURRENT_DATE,29);
INSERT INTO CALENDARIO (ID_COMIC,ID_USUARIO,FECHA_PUBLICAR,NUMERO) VALUES (51,46,CURRENT_DATE,36);

/*
ID_COMIC |TITULO                |PRECIO |FALTANTES |EDITORIAL      |PERIODICIDAD |
---------|----------------------|-------|----------|---------------|-------------|
4        |Deadpool              |53     |          |Marvel Mexico  |mensual      |
36       |Swampthing            |169    |1,5,9,10  |Vértigo México |anual        |
51       |Blade Of The Inmortal |199    |15,39,50  |Panini         |trimestral   |
 */
SELECT c.TITULO,c.PRECIO,e.NOMBRE EDITORIAL,p.DESCRIPCION PERIODICIDAD FROM COMIC c 
INNER JOIN CARRITOCOMPRAS b ON c.ID_COMIC=b.ID_COMIC AND b.ID_USUARIO=46
INNER JOIN PERIODICIDAD p ON c.ID_PERIODICIDAD = p.ID_PERIODICIDAD
INNER JOIN EDITORIAL e ON c.ID_EDITORIAL = e.ID_EDITORIAL;
/*
 TITULO            |PRECIO |EDITORIAL      |PERIODICIDAD |
------------------|-------|---------------|-------------|
N.G. Evangelion   |99     |Panini         |mensual      |
Valerian          |169    |Marvel Mexico  |mensual      |
Pretty Deadly     |36     |Kamite         |bimestral    |
Outcast           |33     |Kamite         |bimestral    |
Outcast           |33     |Kamite         |bimestral    |
Zelda             |169    |Panini         |bimestral    |
One Punch Man     |99     |Panini         |trimestral   |
Crimson           |299    |Kamite         |semestral    |
Crimson           |299    |Kamite         |semestral    |
Southern Bastards |219    |Panini         |semestral    |
Doom Patrol       |169    |Vértigo México |anual        |
 */

SELECT com.TITULO,e.NOMBRE EDITORIAL,p.DESCRIPCION PERIODICIDAD, cal.FECHA_PUBLICAR,cal.NUMERO FROM CALENDARIO cal
INNER JOIN COMIC com ON com.ID_COMIC = cal.ID_COMIC AND cal.ID_USUARIO=47
INNER JOIN PERIODICIDAD p ON com.ID_PERIODICIDAD = p.ID_PERIODICIDAD
INNER JOIN EDITORIAL e ON com.ID_EDITORIAL = e.ID_EDITORIAL;



SELECT com.TITULO,e.NOMBRE EDITORIAL,p.DESCRIPCION PERIODICIDAD, cal.FECHA_PUBLICAR,cal.NUMERO,cal.ID_COMIC FROM CALENDARIO cal
INNER JOIN COMIC com ON com.ID_COMIC = cal.ID_COMIC AND cal.ID_USUARIO=47 AND cal.FECHA_PUBLICAR BETWEEN '2018-07-29' AND '2018-09-09'
INNER JOIN PERIODICIDAD p ON com.ID_PERIODICIDAD = p.ID_PERIODICIDAD
INNER JOIN EDITORIAL e ON com.ID_EDITORIAL = e.ID_EDITORIAL;
/*
 TITULO              |EDITORIAL     |PERIODICIDAD |FECHA_PUBLICAR |NUMERO |
--------------------|--------------|-------------|---------------|-------|
Naruto              |Panini        |mensual      |1954-06-07     |1      |
Zelda               |Panini        |bimestral    |2017-11-09     |3      |
Miss Marvel         |Marvel Mexico |mensual      |1977-05-08     |7      |
Berserk             |Panini        |bimestral    |2018-08-15     |4      |
Alita Battle Angel  |Smash Manga   |quincenal    |2018-08-15     |7      |
Extraordinary X Men |Marvel Mexico |mensual      |2018-08-15     |1      |
Deadpool            |Marvel Mexico |mensual      |2018-08-25     |9      |
Old Man Logan       |Marvel Mexico |mensual      |2018-08-19     |20     |
Deadly Class        |Panini        |trimestral   |2018-08-25     |20     |
 */
SELECT * FROM COMIC WHERE ID_COMIC NOT IN (SELECT ID_COMIC FROM CALENDARIO WHERE ID_USUARIO=47);

SELECT * FROM CALENDARIO WHERE ID_USUARIO = 47;

SELECT c.ID_COMIC,c.TITULO,c.PRECIO,e.NOMBRE EDITORIAL,p.DESCRIPCION PERIODICIDAD,0 CARRITO FROM COMIC c 
INNER JOIN BIBLIOTECA b ON c.ID_COMIC=b.ID_COMIC AND b.ID_USUARIO=46
INNER JOIN PERIODICIDAD p ON c.ID_PERIODICIDAD = p.ID_PERIODICIDAD
INNER JOIN EDITORIAL e ON c.ID_EDITORIAL = e.ID_EDITORIAL
UNION
SELECT c.ID_COMIC,c.TITULO,c.PRECIO,e.NOMBRE EDITORIAL,p.DESCRIPCION PERIODICIDAD, 1 CARRITO FROM COMIC c 
INNER JOIN CARRITOCOMPRAS b ON c.ID_COMIC=b.ID_COMIC AND b.ID_USUARIO=46
INNER JOIN PERIODICIDAD p ON c.ID_PERIODICIDAD = p.ID_PERIODICIDAD
INNER JOIN EDITORIAL e ON c.ID_EDITORIAL = e.ID_EDITORIAL;


SELECT  FROM CARRITOCOMPRAS WHERE ID_USUARIO=46;

ALTER TABLE CARRITOCOMPRAS ADD CONSTRAINT CARRITOCOMPRAS_COMIC_FK
FOREIGN KEY (ID_COMIC) REFERENCES APP.COMIC(ID_COMIC);

ALTER TABLE CARRITOCOMPRAS ADD CONSTRAINT CARRITOCOMPRAS_USUARIOS_FK
FOREIGN KEY (ID_USUARIO) REFERENCES APP.USUARIOS(ID_USUARIO);


DELETE FROM APP.CARRITOCOMPRAS WHERE ID_CARRITO = 100;

SELECT NOMBRE FROM EDITORIAL;

SELECT DESCRIPCION FROM PERIODICIDAD;

SELECT SUM(PRECIO) FROM COMIC WHERE ID_COMIC IN(SELECT ID_COMIC FROM CALENDARIO WHERE ID_USUARIO =47);

SELECT * FROM PERIODICIDAD;