-- Drop table

-- DROP TABLE APP.BIBLIOTECA

CREATE TABLE APP.BIBLIOTECA (
	ID_USUARIO INTEGER NOT NULL,
	ID_COMIC INTEGER NOT NULL,
	FALTANTES VARCHAR(800),
	CONSTRAINT BIBLIOTECA_PK PRIMARY KEY (ID_USUARIO,ID_COMIC),
	CONSTRAINT BIBLIOTECA_COMIC_FK FOREIGN KEY (ID_COMIC) REFERENCES APP.COMIC(ID_COMIC),
	CONSTRAINT BIBLIOTECA_USUARIOS_FK FOREIGN KEY (ID_USUARIO) REFERENCES APP.USUARIOS(ID_USUARIO)
);
CREATE UNIQUE INDEX SQL180725173909620 ON APP.BIBLIOTECA (ID_USUARIO,ID_COMIC);
CREATE INDEX SQL180725174306460 ON APP.BIBLIOTECA (ID_USUARIO);
CREATE INDEX SQL180725174306620 ON APP.BIBLIOTECA (ID_COMIC);

-- Drop table

-- DROP TABLE APP.CALENDARIO

CREATE TABLE APP.CALENDARIO (
	ID_COMIC INTEGER NOT NULL,
	ID_USUARIO INTEGER NOT NULL,
	FECHA_PUBLICAR DATE,
	NUMERO INTEGER DEFAULT 1 NOT NULL,
	CONSTRAINT CALENDARIO_PK PRIMARY KEY (ID_COMIC,ID_USUARIO),
	CONSTRAINT CALENDARIO_COMIC_FK FOREIGN KEY (ID_COMIC) REFERENCES APP.COMIC(ID_COMIC),
	CONSTRAINT CALENDARIO_USUARIOS_FK FOREIGN KEY (ID_USUARIO) REFERENCES APP.USUARIOS(ID_USUARIO)
);
CREATE UNIQUE INDEX SQL180725173607870 ON APP.CALENDARIO (ID_COMIC,ID_USUARIO);
CREATE INDEX SQL180725173607871 ON APP.CALENDARIO (ID_COMIC);
CREATE INDEX SQL180725173607872 ON APP.CALENDARIO (ID_USUARIO);

-- Drop table

-- DROP TABLE APP.CARRITOCOMPRAS

CREATE TABLE APP.CARRITOCOMPRAS (
	ID_CARRITO INTEGER DEFAULT AUTOINCREMENT: start 1 increment 1 NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	ID_COMIC INTEGER NOT NULL,
	ID_USUARIO INTEGER NOT NULL,
	CONSTRAINT CARRITOCOMPRAS_PK PRIMARY KEY (ID_CARRITO),
	CONSTRAINT CARRITOCOMPRAS_COMIC_FK FOREIGN KEY (ID_COMIC) REFERENCES APP.COMIC(ID_COMIC),
	CONSTRAINT CARRITOCOMPRAS_USUARIOS_FK FOREIGN KEY (ID_USUARIO) REFERENCES APP.USUARIOS(ID_USUARIO)
);
CREATE UNIQUE INDEX SQL180816153950000 ON APP.CARRITOCOMPRAS (ID_CARRITO);
CREATE INDEX SQL180816160311800 ON APP.CARRITOCOMPRAS (ID_COMIC);
CREATE INDEX SQL180816160314940 ON APP.CARRITOCOMPRAS (ID_USUARIO);

-- Drop table

-- DROP TABLE APP.COMIC

CREATE TABLE APP.COMIC (
	ID_COMIC INTEGER DEFAULT AUTOINCREMENT: start 1 increment 1 NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	TITULO VARCHAR(200) NOT NULL,
	ID_PERIODICIDAD INTEGER NOT NULL,
	PRECIO DECIMAL(5,0) NOT NULL,
	ID_EDITORIAL INTEGER,
	EN_PUBLICACION SMALLINT,
	NUMERO_INICIAL INTEGER DEFAULT 1 NOT NULL,
	NUMERO_FINAL INTEGER,
	CONSTRAINT COMIC_PK PRIMARY KEY (ID_COMIC),
	CONSTRAINT COMIC_EDITORIAL_FK FOREIGN KEY (ID_EDITORIAL) REFERENCES APP.EDITORIAL(ID_EDITORIAL),
	CONSTRAINT COMIC_PERIODICIDAD_FK FOREIGN KEY (ID_PERIODICIDAD) REFERENCES APP.PERIODICIDAD(ID_PERIODICIDAD)
);
CREATE UNIQUE INDEX SQL180725173317730 ON APP.COMIC (ID_COMIC);
CREATE INDEX SQL180725173317731 ON APP.COMIC (ID_PERIODICIDAD);
CREATE INDEX SQL180725173317732 ON APP.COMIC (ID_EDITORIAL);

-- Drop table

-- DROP TABLE APP.EDITORIAL

CREATE TABLE APP.EDITORIAL (
	ID_EDITORIAL INTEGER DEFAULT AUTOINCREMENT: start 1 increment 1 NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	NOMBRE VARCHAR(100) NOT NULL,
	CONSTRAINT EDITORIAL_PK PRIMARY KEY (ID_EDITORIAL)
);
CREATE UNIQUE INDEX SQL180725172607290 ON APP.EDITORIAL (ID_EDITORIAL);

-- Drop table

-- DROP TABLE APP.PERIODICIDAD

CREATE TABLE APP.PERIODICIDAD (
	ID_PERIODICIDAD INTEGER DEFAULT AUTOINCREMENT: start 1 increment 1 NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	DESCRIPCION VARCHAR(100) NOT NULL,
	TIEMPO INTEGER NOT NULL,
	CONSTRAINT PERIODICIDAD_PK PRIMARY KEY (ID_PERIODICIDAD)
);
CREATE UNIQUE INDEX SQL180725172315560 ON APP.PERIODICIDAD (ID_PERIODICIDAD);

-- Drop table

-- DROP TABLE APP.USUARIOS

CREATE TABLE APP.USUARIOS (
	ID_USUARIO INTEGER DEFAULT AUTOINCREMENT: start 1 increment 1 NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	USUARIO VARCHAR(100) NOT NULL,
	PASSWORD VARCHAR(100) NOT NULL,
	CONSTRAINT USUARIOS_PK PRIMARY KEY (ID_USUARIO)
);
CREATE UNIQUE INDEX SQL180725171825380 ON APP.USUARIOS (ID_USUARIO);
